CREATE DATABASE QuanLyVatTu;
USE QuanLyVatTu;
CREATE TABLE PhieuNhap(
soPn INT AUTO_INCREMENT PRIMARY KEY,
ngayNhap DATETIME
);
CREATE TABLE PhieuXuat(
soPX INT AUTO_INCREMENT PRIMARY KEY,
ngayXuat DATETIME
);
CREATE TABLE VatTu(
maVt INT AUTO_INCREMENT PRIMARY KEY,
tenVT VARCHAR(255)
);
CREATE TABLE NgayCungCap(
maNCC INT AUTO_INCREMENT PRIMARY KEY,
tenNCC VARCHAR(255),
diaChi VARCHAR(255),
soDienThoai VARCHAR(11)
);
CREATE TABLE PhieuNhapChiTiet(
soPn INT REFERENCES PhieuNhap(soPN),
maVt INT REFERENCES VatTu(maVt),
donGiaNhap DOUBLE,
donSoLuongNhap INT,
PRIMARY KEY (soPn, maVt)
);
CREATE TABLE PhieuXuatChiTiet(
soPx INT REFERENCES PhieuXuat(soPx),
maVt INT REFERENCES VatTu(maVt),
donGiaXuat DOUBLE,
donSoLuongXuat INT,
PRIMARY KEY(soPx, maVt)
);
CREATE TABLE DonDatHang(
soDH INT AUTO_INCREMENT PRIMARY KEY,
maNCC INT REFERENCES NgayCungCap(maNCC),
ngayDatHang DATETIME
);
CREATE TABLE ChiTietDonDatHang(
maVt INT REFERENCES VatTu(maVt),
soDH INT REFERENCES DonDatHang(soDH),
PRIMARY KEY (maVt, soDH)
);
